name: task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  get: ^4.6.5
  url_strategy: ^0.2.0
  fluttertoast: ^8.0.8
  connectivity: ^3.0.6
  http: ^0.13.3
  permission_handler: ^9.2.0
  file_picker: ^4.1.6
  extended_image: ^6.3.1
  badges: ^2.0.3

  firebase_storage: ^10.3.11
  firebase_messaging: ^11.2.8



flutter:
  uses-material-design: true

  assets:
    - assets/
